### ISSUE TITLE
unable to sign in or create account

### ISSUE THREAD

**Issue by vedabrat** [tbeddy/tremolonimbus#19]
While accessing https://tremolonimbus.herokuapp.com/#/ from a chrome browser in ubuntu 20.04.
 Clicking on " create an account", I come up to an error that says 
"Displayname can't be blank" listed under the sign up button using the following details to fill out the form:
 standard letters and numbers as a username totally consisting of 11 characters,
a valid email address, 
A password containing letters, numbers, and a special character.

**Comment by tbeddy** [comment]
Thank you so much for filling this bug. I have reproduced the issue and will begin work on it shortly.

**Comment by tbeddy** [comment]
Fixed with commit [4ad59d85d218325441b4537815e65b807e897c32](https://github.com/tbeddy/tremolonimbus/commit/4ad59d85d218325441b4537815e65b807e897c32)
